### ISSUE TITLE
Generation of NSO inventory fails if NSO ENV_VARS not set

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/virlutils#57] opened 2018-08-15 20:30 UTC
**Describe the bug**
If you try to `virl generate nso` and haven't set environment variables for `NSO_HOST` `NSO_USERNAME` and `NSO_PASSWORD` you get an unhelpful error.  

```
$ virl generate nso
Updating NSO....
Exception raised while running your command
Please open an issue and provide this info:
local variable 'input' referenced before assignment
```

**To Reproduce**
Attempt the behavior

**Expected behavior**
Should provide an error that indicates the needed `exports`.

**Desktop (please complete the following information):**
- Mac
- virlutils 0.8.4
- NSO 4.7

**Comment by vleijon** [comment] 2018-08-16 08:25
This was of the things I thought I fixed with my patch, does this still happen for you with that applied?

**Comment by kecorbin** [comment] 2018-09-02 12:53
+1 those fixes from #52 were merged although I have not explicitly tested.  @hpreston can u confirm and close?

**Comment by therk** [comment] 2019-03-10 13:36
The issue is still happens with latest 0.8.4. It should be useful to get a more descriptive error message. 

~ virl generate nso
Updating NSO....
Exception raised while running your command
Please open an issue and provide this info:
local variable 'input' referenced before assignment

**Comment by vleijon** [comment] 2019-03-11 08:43
I am afraid my bugfix was merged a few weeks after 0.8.4.

**Comment by kecorbin** [comment] 2019-03-15 03:17
sorry for the delay @therk can you confim that your issue is resolved if you install from source?  if so i will cut a new release to pypi.  it's probably due anyway for some other stuff

**Comment by kecorbin** [comment] 2019-04-04 18:05
@hpreston @therk this should fixed in pypi releases now

**Closed** 2019-04-04 18:06 UTC
